# Nom du workflow
name: Java CI

# Déclencheurs : Quand le workflow s'exécute ?
on:
  - push         # Lorsqu'un commit est poussé
  - pull_request # Lorsqu'une Pull Request est créée ou mise à jour

# Définition des jobs
jobs:
  build:                   # Nom du job
    runs-on: ubuntu-latest # L'environnement sur lequel le job s'exécute (ici, Ubuntu Linux)

    steps:                 # Les étapes à exécuter dans ce job
      # 1. Cloner le dépôt GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurer Java JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'    # Utilisation de la distribution Java Corretto
          java-version: '23'          # Version de Java (à changer selon votre projet)
          cache: 'gradle'             # Mettre en cache les dépendances Gradle pour accélérer le build

      # 3. Construire et tester le projet avec Gradle
      - name: Build with Gradle
        run: ./gradlew clean build
