#!/usr/bin/sh


# Path to the commit message file
commit_message_file=$1

if ! echo "$commit_message" | grep -qE "^ednova-assignement-2: .+"; then
    echo "ERROR: Commit message must start with 'ednova-assignement-2:' followed by a description."
    exit 1
fi

